name: AWS Configuration

on:
  workflow_dispatch:
    inputs:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
      aws-region:
        description: 'AWS Region'
        required: true

jobs:
  aws-configure:
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        id: set-credentials
        run: |
          aws configure set aws_access_key_id ${{ github.event.inputs.aws-access-key-id }}
          aws configure set aws_secret_access_key ${{ github.event.inputs.aws-secret-access-key }}
          aws configure set region ${{ github.event.inputs.aws-region }}
      
      - name: Run AWS CLI Commands
        id: set-config
        run: |
          aws sts get-caller-identity