name: terraform

on: 
  workflow_dispatch

jobs:
  terraform:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"
      
      
          